mysql:                                                                    # 指定数据库配置
  host: "MYSQL_HOST"
  port: "MYSQL_PORT"
  user: "MYSQL_USER"
  pass: "MYSQL_PASS"
  database: "MYSQL_DATABASE"
time:
  threads: 20                                                             ## 搜索启动的(最多)线程数量
  interval: 1000                                                          ## 所有等待时间统一为 多少 毫秒
ncbi:                                                                     # 与爬虫页面相关的配置
  prefix: "https://pubmed.ncbi.nlm.nih.gov"
  params:
    term: "term"
    page: "page"
    filter: "filter"
  pagesize: 10                                                            ## 返回页面中，每页含有多少条信息
  totalResults: "totalResults"                                            ## 从哪个关键字可以获得“查询结果数”
  ids: "data-chunk-ids"                                                   ## 从哪个关键字可以获得所有的id
